# Generated by Django 5.0.2 on 2024-02-24 08:51

import ckeditor.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='image_goods/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('old_price', models.CharField(max_length=255, verbose_name='Старая цена')),
                ('new_price', models.CharField(max_length=255, verbose_name='Новая цена')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
