# Generated by Django 5.0.2 on 2024-02-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '1) Товар', 'verbose_name_plural': '1) Товары'},
        ),
    ]
