# Generated by Django 5.0.2 on 2024-02-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_team_alter_about_options_teaminline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '2) Команда', 'verbose_name_plural': '2) Команды'},
        ),
    ]
