# Generated by Django 5.0.2 on 2024-02-25 19:49

import ckeditor.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_alter_team_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='employee/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('position', models.CharField(max_length=255, verbose_name='должность')),
                ('experience', models.PositiveSmallIntegerField(verbose_name='опыт')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': '3) Cотрудник ',
                'verbose_name_plural': '3)  Сотрудники',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default=1, upload_to='team/', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TeamInline',
        ),
    ]
