# Generated by Django 5.0.2 on 2024-02-26 07:00

import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_remove_employee_image_employee_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='image_team/', verbose_name='Фото')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('function', ckeditor.fields.RichTextField(verbose_name='Особые функциональности')),
                ('descritions', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.AddField(
            model_name='teaminline',
            name='place_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_inline', to='secondary.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teaminline',
            unique_together={('place_info', 'name')},
        ),
    ]
