# Generated by Django 5.0.2 on 2024-03-02 11:40

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_teaminline_delete_employee_remove_team_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='faq/', verbose_name='Фото')),
                ('descritions', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': ('Часто задаваемый вопрос',),
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
    ]
