# Generated by Django 5.0.2 on 2024-03-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_inline', to='secondary.faq')),
            ],
            options={
                'unique_together': {('place_info', 'question')},
            },
        ),
    ]
