# Generated by Django 5.0.2 on 2024-03-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_faqinline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='descritions',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='image',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(default=1, verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.CharField(default=1, max_length=255, verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FaqInline',
        ),
    ]
