# Generated by Django 5.0.2 on 2024-02-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo_image/', verbose_name='Логотип')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('facebook', models.URLField(verbose_name='Facebook URL')),
                ('twitter', models.URLField(verbose_name='Twitter URL')),
                ('instagram', models.URLField(verbose_name='Instagram URL')),
            ],
            options={
                'verbose_name': 'Основная настройка',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
