# Generated by Django 5.0.2 on 2024-02-23 06:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_description', ckeditor.fields.RichTextField(verbose_name='Главное Описание')),
                ('image', models.ImageField(upload_to='image_new_arrival/', verbose_name='Фото продукта')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Новое поступление',
                'verbose_name_plural': 'Новые поступления',
            },
        ),
    ]
