# Generated by Django 5.0.2 on 2024-02-23 06:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_newarrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': '5) Самое актуальное',
                'verbose_name_plural': '5) Самое октуальное',
            },
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '3) Коллекция', 'verbose_name_plural': '3) Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='newarrival',
            options={'verbose_name': '4) Новое поступление', 'verbose_name_plural': '4) Новые поступления'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '1) Основная настройка', 'verbose_name_plural': '1) Основные настройки'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': '2) Слайд ', 'verbose_name_plural': '2) Слайды'},
        ),
    ]
