# Generated by Django 5.0.2 on 2024-02-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_news_newsinline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '7) Новость', 'verbose_name_plural': '7) Новости'},
        ),
    ]
