# Generated by Django 5.0.2 on 2024-02-26 06:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='schedule',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Расписание'),
            preserve_default=False,
        ),
    ]
